// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function isValidSupabaseKey(key: string): boolean {
  return key.startsWith("eyJ") || isNewSupabaseApiKey(key);
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    if (!isValidSupabaseKey(supabaseKey)) {
      // Local offline mode or placeholder key: return clean response to use local fallback seamlessly
      const urlString =
        typeof input === "string" ? input : input instanceof Request ? input.url : "";
      const body = urlString.includes("/auth/v1") ? { user: null, session: null } : [];
      return new Response(JSON.stringify(body), {
        status: 200,
        headers: {
          "Content-Type": "application/json",
          "Content-Range": "0-0/0",
        },
      });
    }

    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);

    try {
      const response = await fetch(input, { ...init, headers });
      if (response.status === 401) {
        const urlString =
          typeof input === "string" ? input : input instanceof Request ? input.url : "";
        const body = urlString.includes("/auth/v1") ? { user: null, session: null } : [];
        return new Response(JSON.stringify(body), {
          status: 200,
          headers: {
            "Content-Type": "application/json",
            "Content-Range": "0-0/0",
          },
        });
      }
      return response;
    } catch (err) {
      const urlString =
        typeof input === "string" ? input : input instanceof Request ? input.url : "";
      const body = urlString.includes("/auth/v1") ? { user: null, session: null } : [];
      return new Response(JSON.stringify(body), {
        status: 200,
        headers: {
          "Content-Type": "application/json",
          "Content-Range": "0-0/0",
        },
      });
    }
  };
}

function createSupabaseClient() {
  const SUPABASE_URL =
    (typeof import.meta !== "undefined" && import.meta.env
      ? import.meta.env.VITE_SUPABASE_URL
      : undefined) ||
    (typeof process !== "undefined" && process.env
      ? process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL
      : undefined) ||
    "https://placeholder.supabase.co";

  const SUPABASE_PUBLISHABLE_KEY =
    (typeof import.meta !== "undefined" && import.meta.env
      ? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY
      : undefined) ||
    (typeof process !== "undefined" && process.env
      ? process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
        process.env.SUPABASE_PUBLISHABLE_KEY ||
        process.env.VITE_SUPABASE_ANON_KEY ||
        process.env.SUPABASE_ANON_KEY
      : undefined) ||
    "placeholder";

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Please check your environment variables.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const customStorage =
    typeof window !== "undefined"
      ? {
          getItem: (key: string) => {
            return window.localStorage.getItem(key) || window.sessionStorage.getItem(key);
          },
          setItem: (key: string, value: string) => {
            if (window.localStorage.getItem("remember_me") === "true") {
              window.localStorage.setItem(key, value);
            } else {
              window.sessionStorage.setItem(key, value);
            }
          },
          removeItem: (key: string) => {
            window.localStorage.removeItem(key);
            window.sessionStorage.removeItem(key);
          },
        }
      : undefined;

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: customStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
